<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Main\Module'                        => __DIR__ . '/Module.php',
    'Main\Controller\IndexController' => __DIR__ . '/src/Main/Controller/IndexController.php',
    'MainTest\Framework\TestCase'        => __DIR__ . '/tests/Main/Framework/TestCase.php',
    'MainTest\SampleTest'                => __DIR__ . '/tests/Main/SampleTest.php',
);
